let sonstigeEinnahmen = {
    art: "",
    ausserordentlicheEinkuenfte: false,
    beitrag: 0,
    betrag: 0,
    gewerbebetrieb: false,
    jahresBeitrag: 0,
    kapitalvermogen: false,
    landUndForstwirtschaft: false,
    monatsBeitrag: 0,
    nichtselbststaendigeTaetigkeit: false,
    notizen: "",
    selbststaendigeTaetigkeit: false,
    sonstigeEinkuenfte: "",
    sonstigeEinkuenfte22Renten: false,
    steuerfreieEinnahmen: false,
    steuerfreieEinnahmenUnterProgressionsvorbehalt: false,
    vermietungUndVerpachtung: false,
    versicherungsbeginn: "",
    versicherungsende: "",
    zahlweise: "",
  };
  
  let einkommenGehalt = {
    angebotsType: "VERTRAG",
    beitrag: 0,
    bonuszahlungAuszahlungsmonat: "",
    dienstwagenGesamtbrutto: "",
    dienstwagenSozialversicherung: "",
    dienstwagenSteuer: "",
    externalProduktId: "",
    fahrtkostenSozialversicherung: "",
    fahrtkostenSteuer: "",
    feiertagszuschlagGesamtbrutto: "",
    feiertagszuschlagSozialversicherung: "",
    feiertagszuschlagSteuer: "",
    gesellschaft: "",
    gewinnbeteiligungAuszahlungsmonat: "",
    grundgehalt: 0,
    grundgehaltGesamtbrutto: "",
    grundgehaltSozialversicherung: "",
    grundgehaltSteuer: "",
    jahresBeitrag: 0,
    jobradGesamtbrutto: "",
    jobradSozialversicherung: "",
    jobradSteuer: "",
    kitaGesamtbrutto: "",
    kitaSozialversicherung: "",
    kitaSteuer: "",
    lastModified: "",
    lohnAnzahlProJahr: 0,
    lohnBrutto: 0,
    lohnBruttoProJahr: 0,
    monatsBeitrag: 0,
    nachtzuschlagGesamtbrutto: "",
    nachtzuschlagSozialversicherung: "",
    nachtzuschlagSteuer: "",
    notizen: "",
    provisionGesamtbrutto: "",
    provisionSozialversicherung: "",
    provisionSteuer: "",
    sachbezugGesamtbrutto: "",
    sachbezugSozialversicherung: "",
    sachbezugSteuer: "",
    sonstigesAuszahlungsmonat: "",
    sonstigesBruttoGesamtbrutto: "",
    sonstigesBruttoSozialversicherung: "",
    sonstigesBruttoSteuer: "",
    tarifBezeichnung: "",
    tarifTypeId: "EINKOMMEN_GEHALT",
    urlaubsgeldAuszahlungsmonat: "Juni",
    variablerBezugGesamtbrutto: "",
    variablerBezugSozialversicherung: "",
    variablerBezugSteuer: "",
    versicherungsnehmerId: "",
    vwlGesamtbrutto: "",
    vwlSozialversicherung: "",
    vwlSteuer: "",
    weihnachtsgeldAuszahlungsmonat: "",
  };
  let einkommenGeringverdiener = {
    eigenbeitraegeZurSV: false,
    einkommen: 0,
    anzahlMonateProJahr: 0,
    einkommen: 0,
  };
  let einkommenSelbststaendig = {
    beitrag: 0,
    jaehrlichVersteuerndesEinkommen: 0,
    jaehrlicherGewinnNachSteuer: 0,
    jaehrlichesEinkommenGewerbebetrieb: 0,
    jahresBeitrag: 0,
    monatlichesEinkommenGewerbebetrieb: 0,
    monatsBeitrag: 0,
    umsatzExklSteuer: 0,
    umsatzInklSteuer: 0,
  };
  let ausgaben = {
    beitrag: 0,
    jahresBeitrag: 0,
    kostenArzt: 0,
    kostenBus: 0,
    kostenFreizeit: 0,
    kostenHausiere: 0,
    kostenHobbies: 0,
    kostenKfz: 0,
    kostenKfzKraftstoff: 0,
    kostenKfzSteuer: 0,
    kostenKleidung: 0,
    kostenKonsum: 0,
    kostenKosmetik: 0,
    kostenMusikschule: 0,
    kostenSchule: 0,
    kostenSonstiges: 0,
    kostenStrom: 0,
    kostenTV: 0,
    kostenTaschengeld: 0,
    kostenUnterhalt: 0,
    kostenVerein: 0,
    kostenZeitungen: 0,
    lebenshaltung: 0,
    monatsBeitrag: 0,
    nebenkosten: 0,
    tarifTypeId: "AUSGABEN",
  };
  
  let automobilclub = {
    ngebotsType: "VERTRAG",
    anzahlVersicherterKfz: 0,
    beitrag: 0,
    createdOn: "",
    externalProduktId: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    monatsBeitrag: 0,
    notizen: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versicherungsbeginn: "",
    zahlweise: "",
  };
  let sonstigeZahlungsverpflichtigungen = {
    analyseId: "",
    angebotsType: "",
    art: "",
    beginZahlung: "",
    beitrag: 0,
    endeZahlung: "",
    externalProduktId: "",
    gesellschaft: "",
    jahresBeitrag: 0,
    monatsBeitrag: 0,
    notizen: "",
    rate: 0,
    tarifBezeichnung: "",
    tarifTypeId: "",
    versicherungsnummer: "",
    verwendungszweck: "",
    zahlweise: "",
  };
  let konsumKredit = {
    anfangshoehe: 0,
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    anschriftWohnhaft3Jahren: false,
    beitrag: 0,
    beschreibung: "",
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    gesellschaft: "",
    jahresBeitrag: 0,
    leistung: 0,
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    rate: 0,
    restschuld: 0,
    shortDescription: "",
    standVom: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerBeide: false,
    versicherungsnummer: "",
    versicherungssumme: 0,
    verwendung: "",
    vorherigeAnschrift: "",
    zahlweise: "",
    zinssatzTyp: "",
  };
  
  let bankprodukte = {
    angebotsType: "",
    anlageart: "",
    anlageartSonstiges: "",
    beitrag: 0,
    eigenvertrag: false,
    einmalbeitrag: 0,
    externalProduktId: "",
    fremdvertrag: false,
    gesellschaft: "",
    jahresBeitrag: 0,
    logoname: "",
    monatsBeitrag: 0,
    notizen: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerBeide: false,
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    wertZum: "",
    zahlweise: "",
  };
  let vwl = {
    aganteil: 0,
    analyseId: "",
    ananteil: 0,
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    art: "",
    bausparsumme: 0,
    beitrag: 0,
    beschreibung: "",
    besparungDurch: "",
    besparungPercentage: 0,
    comment: "",
    darlehenszins: 0,
    dauerzulagenantrag: false,
    eigenvertrag: false,
    ersparnis: false,
    fremdvertrag: false,
    gekuendigtDurch: "",
    gesellschaft: "",
    guthaben: 0,
    guthabenzins: 0,
    id: "",
    jahresBeitrag: 0,
    lastModified: "0",
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    riesterzulage: "",
    riesterzulageLetztmaligBetrag: 0,
    shortDescription: "",
    sparzulageAN: false,
    tarifBezeichnung: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerBeide: false,
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    vwlJaNein: false,
    wop: false,
    zahlweise: "MONATLICH",
  };
  let immobilienbestand = {
    aktuellerwert: 0,
    baujahr: "",
    beitrag: 0,
    denkmalschutz: false,
    erwerbsjahr: "",
    externalProduktId: "",
    ferienimmobilie: false,
    garantieProQm: 0,
    gesellschaft: "",
    gleitenderNeuwert: 0,
    hasUeberschuss: false,
    hausgeld: 0,
    immobilienart: "",
    jahresBeitrag: 0,
    kaltmiete: 0,
    kaufpreisEuro: 0,
    mietpool: false,
    mietpoolEnde: "",
    monatlicheMieteinkuenfte: 0,
    monatsBeitrag: 0,
    nettobelastungMtlCa: 0,
    notizen: "",
    nutzung: false,
    objektnotizen: "",
    pflegeimmobilie: false,
    restschuld: false,
    stellplatz: false,
    stellplatzKaufpreis: 0,
    stellplatzMiete: 0,
    tarifBezeichnung: "",
    tarifTypeId: "",
    ueberschussMtlCa: 0,
    versicherungsnehmerBeide: false,
    versicherungsnehmerId: "",
    voraussichtlichSchuldenfrei: "",
    wohnflaeche: 0,
    wohnungsnummer: "",
  };
  let beteiligungenAiF = {
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    anlageform: "",
    anlageformSonstige: "",
    beginnJahr: 0,
    beitrag: 0,
    beschreibung: "",
    beteiligungssumme: 0,
    comment: "",
    createdOn: "17.11.2021 13:47:35",
    eigenvertrag: false,
    einmalbeitrag: 0,
    endeJahr: 0,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    prognose: 0,
    shortDescription: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versicherungsnummer: "",
    verwendungszweck: "",
    wert: 0,
    wertZum: "",
    zahlweise: "",
  };
  let buEuGfk = {
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "VERTRAG",
    art: "EU",
    beitrag: 0,
    beschreibung: "",
    bruttobeitrag: 0,
    comment: "",
    createdOn: "",
    dynamik: true,
    dynamikProzent: 0,
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    renteGarantiert: 0,
    rentenleistung: 0,
    rueckkaufswert: 0,
    shortDescription: "",
    tarifBezeichnung: "",
    tarifTypeId: "BU",
    versichertePersonId: "",
    versichertePersonSonstige: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnummer: "",
    zahlweise: "",
  };
  let unfall = {
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    anzahlVP: 0,
    anzpers: 0,
    beitrag: 0,
    bergungskosten: 0,
    beschreibung: "",
    comment: "",
    dynamik: false,
    dynamik2: false,
    dynamik3: false,
    dynamik4: false,
    dynamik5: false,
    dynamik6: true,
    dynamikProzent: 0,
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    genesungsgeld: 0,
    gesellschaft: "",
    grundsumme: 0,
    id: "",
    invaliditaetssumme: 0,
    jahresBeitrag: 0,
    krankenhaustagegeld: 0,
    krankentagegeld: 0,
    krankentagegeldtag: 0,
    krankentagegeldtag2: 0,
    krankentagegeldtag3: 0,
    krankentagegeldtag4: 0,
    krankentagegeldtag5: 0,
    krankentagegeldtag6: 0,
    lastModified: "",
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    operationen: 0,
    progression: 0,
    risikogruppe: "",
    risikogruppe2: "",
    risikogruppe3: "",
    risikogruppe4: "",
    risikogruppe5: "",
    risikogruppe6: "",
    rueckgewaehr: false,
    rueckkaufswert: 0,
    shortDescription: "",
    sonstigeLeistungen: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    tarifgruppe: "0",
    tarifgruppe2: "0",
    tarifgruppe3: "0",
    tarifgruppe4: "0",
    tarifgruppe5: "0",
    tarifgruppe6: "0",
    teilbeitrag: 0,
    teilbeitrag2: 0,
    teilbeitrag3: 0,
    teilbeitrag4: 0,
    teilbeitrag5: 0,
    teilbeitrag6: 0,
    todesfallsumme: 0,
    uebergangsleistung: 0,
    unfallrente: 0,
    unfallrenteAb50Check: false,
    unfallrenteAb50Check2: false,
    unfallrenteAb50Check3: false,
    unfallrenteAb50Check4: false,
    unfallrenteAb50Check5: false,
    unfallrenteAb50Check6: false,
    unfallrenteAb50Euro: 0,
    unfallrenteAbXCheck: false,
    unfallrenteAbXCheck2: false,
    unfallrenteAbXCheck3: false,
    unfallrenteAbXCheck4: false,
    unfallrenteAbXCheck5: false,
    unfallrenteAbXCheck6: false,
    unfallrenteAbXEuro: 0,
    unfallrenteAbXProzent: 0,
    versichertePerson: { id: "", nachname: "", vorname: "" },
    versichertePersonId: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnummer: "",
    vorschaedenAnzahl: 0,
    vorschaedenHoehe: 0,
    vorschaedenNotiz: "",
    zahlweise: "",
  };
  let todesfall = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    art: "",
    beitrag: 0,
    beitragsanteilBU: 0,
    beitragsbefreiungBU: false,
    beschreibung: "",
    bruttobeitrag: 0,
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: false,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    integrierteBuRenten: false,
    integrierteBuRentenBetrag: 0,
    jahresBeitrag: 0,
    lastModified: "",
    leistung: 0,
    logoname: "",
    monatsBeitrag: 0,
    motorradfahrer: false,
    name: "",
    notizen: "",
    raucher: false,
    shortDescription: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versichertePersonBeide: false,
    versichertePersonSonstige: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    versicherungssumme: 0,
    versicherungssummeLineare: false,
    vertragAbgetreten: false,
    zahlweise: "",
  };
  let schwereKrankheiten = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    auszahlung: "",
    beitrag: 0,
    beschreibung: "",
    bruttobeitrag: 0,
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    leistungssummeKrankheit: 0,
    leistungssummeKrankheitAuszahlung: "",
    leistungssummeTod: 0,
    leistungssummeTodAuszahlung: "",
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    rueckkaufswert: 0,
    shortDescription: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versichertePersonId: "",
    versichertePersonSonstige: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    zahlweise: "",
  };
  let privatePflegeversicherung = {
    ambulantEqStationaer: false,
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    art: "",
    beitrag: 0,
    beschreibung: "",
    comment: "",
    createdOn: "",
    dynamik: false,
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    leistungIn: "",
    leistungProTag: false,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    pflegebahr: false,
    shortDescription: "",
    staatlichGefoerdert: false,
    tarifBezeichnung: "",
    tarifTypeId: "",
    versichertePersonId: "",
    versichertePersonSonstige: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    zahlweise: "",
  };
  let gesetzlicheKranken = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    beitrag: 0,
    beschreibung: "",
    bonusprogramm: "",
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    gesellschaft: "",
    gkvLeistungsbonus: 0,
    gkvZusatz: false,
    gkvZusatzBeitrag: 0,
    gkvZusatzsatz: 0,
    id: "",
    jahresBeitrag: 0,
    kTHoehe: 0,
    kTTag: 0,
    kinder: false,
    lastModified: "",
    logoname: "",
    mitKT: false,
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    shortDescription: "",
    status: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versicherungsbeginn: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    zusatzleistungen: "",
  };
  let privateKranken = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    anzahlVP: 0,
    art: "0",
    beitrag: 0,
    beitragVP: 0,
    beschreibung: "",
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    einbettzimmer: "",
    einbettzimmer2: "",
    einbettzimmer3: "",
    einbettzimmer4: "",
    einbettzimmer5: "",
    einbettzimmer6: "",
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: true,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    krankentagegeld1: 0,
    krankentagegeld2: 0,
    krankentagegeldtag1: 0,
    krankentagegeldtag2: 0,
    kurtagegeld: 0,
    lastModified: "",
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    primaerarztprinzip: false,
    primaerarztprinzip2: false,
    primaerarztprinzip3: false,
    primaerarztprinzip4: false,
    primaerarztprinzip5: false,
    primaerarztprinzip6: false,
    rueckerstattung: "",
    rueckerstattung2: "",
    rueckerstattung3: "",
    rueckerstattung4: "",
    rueckerstattung5: "",
    rueckerstattung6: "",
    sb: 0,
    sbAmbulant: true,
    sbAmbulant2: true,
    sbAmbulant3: true,
    sbAmbulant4: true,
    sbAmbulant5: true,
    sbAmbulant6: true,
    sbStationaer: true,
    sbStationaer2: true,
    sbStationaer3: true,
    sbStationaer4: true,
    sbStationaer5: true,
    sbStationaer6: true,
    sbZahn: true,
    shortDescription: "",
    tarifBezeichnung: "Tarifbezeichnung",
    tarifTypeId: "KVV",
    tarifgruppe: "7634",
    tarifname: "5321",
    tarifname2: "",
    tarifname3: "",
    tarifname4: "",
    tarifname5: "",
    tarifname6: "",
    versichertePersonId: "",
    versichertePersonSonstige: "",
    versicherungsbeginn: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    zahlweise: "",
    zahnbehandlung: 0,
    zahnersatz: 0,
  };
  let kvZusatz = {
    altersrueckstellungAmbulant: false,
    altersrueckstellungAmbulant2: false,
    altersrueckstellungAmbulant3: false,
    altersrueckstellungAmbulant4: false,
    altersrueckstellungAmbulant5: false,
    altersrueckstellungAmbulant6: false,
    altersrueckstellungKT: false,
    altersrueckstellungKT2: false,
    altersrueckstellungKT3: false,
    altersrueckstellungKT4: false,
    altersrueckstellungKT5: false,
    altersrueckstellungKT6: false,
    altersrueckstellungStationaer: false,
    altersrueckstellungStationaer2: false,
    altersrueckstellungStationaer3: false,
    altersrueckstellungStationaer4: false,
    altersrueckstellungStationaer5: false,
    altersrueckstellungStationaer6: false,
    altersrueckstellungZahn: false,
    altersrueckstellungZahn2: false,
    altersrueckstellungZahn3: false,
    altersrueckstellungZahn4: false,
    altersrueckstellungZahn5: false,
    altersrueckstellungZahn6: false,
    ambulanteOp: false,
    ambulanteOp2: false,
    ambulanteOp3: false,
    ambulanteOp4: false,
    ambulanteOp5: false,
    ambulanteOp6: false,
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    anzahlReinigungenProJahr: 0,
    anzahlVP: 0,
    art: "",
    auslandsreiseKV: false,
    auslandsreiseKV2: false,
    auslandsreiseKV3: false,
    auslandsreiseKV4: false,
    auslandsreiseKV5: false,
    auslandsreiseKV6: false,
    beitrag: 0,
    beitragDental: 0,
    beitragKT: 0,
    beitragStationaer: 0,
    beitragsrueckerstattung: "",
    beitragsrueckerstattung2: "",
    beitragsrueckerstattung3: "",
    beitragsrueckerstattung4: "",
    beitragsrueckerstattung5: "",
    beitragsrueckerstattung6: "",
    beschreibung: "",
    brille: 0,
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersatzkrankenhaustagegeld: 0,
    ersparnis: false,
    erstattung: "",
    erstattung2: "",
    erstattung3: "",
    erstattung4: "",
    erstattung5: "",
    erstattung6: "",
    externalProduktId: "",
    fremdvertrag: false,
    gekuendigtDurch: "",
    gesellschaft: "",
    gkvZuzahlungen: "",
    gkvZuzahlungen2: "",
    gkvZuzahlungen3: "",
    gkvZuzahlungen4: "",
    gkvZuzahlungen5: "",
    gkvZuzahlungen6: "",
    heilpraktiker: false,
    heilpraktiker2: false,
    heilpraktiker3: false,
    heilpraktiker4: false,
    heilpraktiker5: false,
    heilpraktiker6: false,
    heilpraktikerLeistung: 0,
    hilfsmittel: false,
    hilfsmittel2: false,
    hilfsmittel3: false,
    hilfsmittel4: false,
    hilfsmittel5: false,
    hilfsmittel6: false,
    hoergeraete: false,
    hoergeraete2: false,
    hoergeraete3: false,
    hoergeraete4: false,
    hoergeraete5: false,
    hoergeraete6: false,
    hufeland: false,
    hufeland2: false,
    hufeland3: false,
    hufeland4: false,
    hufeland5: false,
    hufeland6: false,
    id: "",
    inklAmbulant: false,
    inklAmbulant2: false,
    inklAmbulant3: false,
    inklAmbulant4: false,
    inklAmbulant5: false,
    inklAmbulant6: false,
    inklKHT: false,
    inklKHT2: false,
    inklKHT3: false,
    inklKHT4: false,
    inklKHT5: false,
    inklKHT6: false,
    inklKT: false,
    inklKT2: false,
    inklKT3: false,
    inklKT4: false,
    inklKT5: false,
    inklKT6: false,
    inklStationaer: false,
    inklStationaer2: false,
    inklStationaer3: false,
    inklStationaer4: false,
    inklStationaer5: false,
    inklStationaer6: false,
    inklZahn: false,
    inklZahn2: false,
    inklZahn3: false,
    inklZahn4: false,
    inklZahn5: false,
    inklZahn6: false,
    jahresBeitrag: 0,
    kieferorthopaedie: false,
    kieferorthopaedie2: false,
    kieferorthopaedie3: false,
    kieferorthopaedie4: false,
    kieferorthopaedie5: false,
    kieferorthopaedie6: false,
    krankenhaustagegeld: 0,
    krankentagegeld1: 0,
    krankentagegeld2: 0,
    krankentagegeldtag1: 0,
    krankentagegeldtag2: 0,
    kuendigungszeitpunkt: "",
    kur: false,
    kur2: false,
    kur3: false,
    kur4: false,
    kur5: false,
    kur6: false,
    lasik: 0,
    lastModified: "",
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    psychotherapie: false,
    psychotherapie2: false,
    psychotherapie3: false,
    psychotherapie4: false,
    psychotherapie5: false,
    psychotherapie6: false,
    regelversorgung: false,
    regelversorgung2: false,
    regelversorgung3: false,
    regelversorgung4: false,
    regelversorgung5: false,
    regelversorgung6: false,
    reinigungLeistung: 0,
    sehhilfe: false,
    sehhilfe2: false,
    sehhilfe3: false,
    sehhilfe4: false,
    sehhilfe5: false,
    sehhilfe6: false,
    sehhilfeJahre: 0,
    shortDescription: "",
    sonstigeErstattung: "",
    sonstigeErstattung2: "",
    sonstigeErstattung3: "",
    sonstigeErstattung4: "",
    sonstigeErstattung5: "",
    sonstigeErstattung6: "",
    stationaer: "",
    stationaer2: "",
    stationaer3: "",
    stationaer4: "",
    stationaer5: "",
    stationaer6: "",
    tarifAmbulant: "",
    tarifAmbulant2: "",
    tarifAmbulant3: "",
    tarifAmbulant4: "",
    tarifAmbulant5: "",
    tarifAmbulant6: "",
    tarifBezeichnung: "",
    tarifKT: "",
    tarifKT2: "",
    tarifKT3: "",
    tarifKT4: "",
    tarifKT5: "",
    tarifKT6: "",
    tarifStationaer: "",
    tarifStationaer2: "",
    tarifStationaer3: "",
    tarifStationaer4: "",
    tarifStationaer5: "",
    tarifStationaer6: "",
    tarifStationair: "",
    tarifTypeId: "",
    tarifZahn: "",
    tarifZahn2: "",
    tarifZahn3: "",
    tarifZahn4: "",
    tarifZahn5: "",
    tarifZahn6: "",
    tarifgruppe: "",
    versichertePersonId: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnummer: "",
    zahlweise: "",
    zahnbehandlung: 34,
    zahnersatz: 23,
  };
  let privathaftpflicht = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    beitrag: 0,
    beschreibung: "",
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    einschlussEhrenamt: false,
    einschlussSchluesselBeruflich: false,
    einschlussSchluesselPrivat: false,
    einschlussTagesmutter: false,
    ersparnis: false,
    externalProduktId: "",
    forderungsausfall: false,
    fremdvertrag: false,
    gefaelligkeitsschaeden: false,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    inkludiertInBetriebsHV: false,
    jahresBeitrag: 0,
    lastModified: "",
    lehrerhaftpflicht: false,
    leistung: 0,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    oeffentlicherDienst: false,
    sb: 0,
    schadenersatzrechtsschutz: false,
    schluesselschadenSumme: 0,
    shortDescription: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    tarifgruppe: "",
    versichertePersonId: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    versicherungssumme: 0,
    vorschaedenAnzahl: 0,
    vorschaedenHoehe: 0,
    vorschaedenNotiz: "",
    zahlweise: "",
  };
  let hundehalterhaftpflicht = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    anzahl: "",
    beitrag: 0,
    beschreibung: "",
    chipnummer: "",
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    farbe: "",
    fremdvertrag: false,
    geburtsdatum: "",
    gekuendigtDurch: "",
    geschlecht: "",
    gesellschaft: "",
    hunderasse1: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    leistung: 0,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    oeffentlicherDienst: false,
    sb: 0,
    shortDescription: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    tarifgruppe: "",
    tiername: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnummer: "",
    versicherungssumme: 0,
    vorschaedenAnzahl: 0,
    vorschaedenHoehe: 0,
    vorschaedenNotiz: "",
    zahlweise: "",
  };
  let pferdehalterhaftpflicht = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    anzahl: 0,
    beitrag: 0,
    beschreibung: "",
    chipnummer: "",
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    farbe: "",
    fremdvertrag: false,
    geburtsdatum: "",
    gekuendigtDurch: "",
    geschlecht: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    leistung: 0,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    rasse: "",
    reitverein: false,
    sb: 0,
    shortDescription: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    tarifgruppe: "",
    tiername: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    versicherungssumme: 0,
    vorschaedenAnzahl: 0,
    vorschaedenHoehe: 0,
    vorschaedenNotiz: "",
    zahlweise: "",
  };
  let hausrat = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    aquarium: false,
    beitrag: 0,
    beschreibung: "",
    ceran: false,
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    elementar: false,
    ersparnis: false,
    externalProduktId: "",
    fahrrad: "",
    fahrradWert: 0,
    fremdvertrag: false,
    gekuendigtDurch: "",
    gesellschaft: "",
    glasflaeche: false,
    groesse: 0,
    hausnummer: "",
    iart: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    leistung: 0,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    oeffentlicherDienst: false,
    plz: "",
    sb: 0,
    shortDescription: "",
    stadt: "",
    staendigBewohnt: false,
    strasse: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    tarifgruppe: "",
    ueberspannung: "",
    unterversicherungsverzicht: false,
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    versicherungssumme: 0,
    vorschaedenAnzahl: 0,
    vorschaedenHoehe: 0,
    vorschaedenNotiz: "",
    wasserbett: false,
    wertsachen: "0",
    wohnflaeche: 0,
    zahlweise: "",
  };
  let rechtschutz = {
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    beitrag: 0,
    beratung: false,
    beruf: false,
    beschreibung: "",
    comment: "",
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fremdvertrag: false,
    gekuendigtDurch: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    leistung: 0,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    oeffentlicherDienst: false,
    privat: false,
    sb: 0,
    shortDescription: "",
    sonstiges: "",
    strafrechtsschutz: false,
    tarifBezeichnung: "",
    tarifTypeId: "",
    tarifgruppe: "",
    telAnwaltErstberatung: false,
    unbegrenzt: false,
    verkehr: false,
    vermieter: false,
    versichertePersonId: "",
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    versicherungssumme: 0,
    vorschaedenAnzahl: 0,
    vorschaedenHoehe: 0,
    vorschaedenNotiz: "",
    wohnungselbst: false,
    wug: false,
    zahlweise: "",
  };
  let wohngebaeude = {
    ableitungsrohre: false,
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    bauartklasse: "",
    baujahr: 0,
    bedachungHart: false,
    bedachungSonstiges: false,
    bedachungSonstigesText: "",
    bedachungWeich: false,
    beitrag: 0,
    beschreibung: "",
    carport: 0,
    comment: "",
    createdOn: "",
    dachart: "",
    eigenbedarf: false,
    eigenvertrag: false,
    elementar: false,
    ersparnis: false,
    externalProduktId: "",
    fertighausgruppe: "",
    feuer: false,
    feuerhemmungFh30: false,
    feuerhemmungFh60: false,
    feuerhemmungSonstiges: false,
    feuerhemmungSonstigesText: "",
    feuerhemmungUnbekannt: false,
    fremdvertrag: false,
    fussbodenheizung: 0,
    garagen: 0,
    garagenSonstige: 0,
    gebaeudeart: "",
    gekuendigtDurch: "",
    gesellschaft: "",
    glasflaeche: false,
    grundstueckszubehoer: "",
    hagel: false,
    hausnummer: "",
    id: "",
    jahresBeitrag: 0,
    keller: false,
    lastModified: "",
    leitungswasser: false,
    logoname: "",
    monatsBeitrag: 0,
    name: "",
    neubausumme: 0,
    notizen: "",
    nutzung: "",
    oeffentlicherDienst: false,
    plz: "",
    qmDachgeschoss: 0,
    qmErdgeschoss: 0,
    qmKellergeschoss: 0,
    qmObergeschoss: "",
    qmObergeschoss2: "",
    qmUnterkellert: "",
    schaeden: "",
    schwimmbadPos: 0,
    shortDescription: "",
    sonstigeLeistungen: "",
    stadt: "",
    staendigBewohnt: false,
    strasse: "",
    sturm: false,
    tarifBezeichnung: "",
    tarifTypeId: "",
    tarifgruppe: "",
    teilunterkellert: false,
    vermietet: false,
    versicherungsbeginn: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    vorschaedenNotiz: "",
    waendeBrennbar: false,
    waendeMassiv: false,
    waendeNichtBrennbar: false,
    waendeNichtMassiv: false,
    waendeSonstiges: false,
    waendeSonstigesText: "",
    wohneinheiten: "",
    wohnflaeche: 0,
    zahlweise: "",
  };
  let KFZ = {
    akz1: "",
    akz2: "",
    akz3: "",
    analyseId: "",
    angebot_berater: false,
    angebot_gutachten: false,
    angebot_sonstiges: false,
    angebotsType: "",
    automobilclub: "",
    beitrag: 0,
    beschreibung: "",
    car_abs: false,
    car_abstellort_abgeschlossen: false,
    car_anhaengerbetrieb: false,
    car_betriebsausgabe: false,
    car_gap: false,
    car_hsn: "",
    car_schlingerdaempfung: false,
    car_sozius: false,
    car_tsn: "",
    car_vorschaeden_haft: (3)[(0, 0, 0)],
    car_vorschaeden_kasko_teil: (3)[(0, 0, 0)],
    car_vorschaeden_kasko_voll: (3)[(0, 0, 0)],
    car_vorsteuerabzug: false,
    car_wegfahrsperre: false,
    car_zw_sf_haft_erst: "",
    car_zw_sf_kasko_erst: "",
    car_zw_vorschaeden_erst: false,
    comment: "",
    contract_auslandsschutz: false,
    contract_beginn: "",
    contract_fahrerschutz: false,
    contract_rabattschutz: false,
    contract_schutzbrief: false,
    contract_sf_haft: "",
    contract_sf_kasko: "",
    contract_werkstattbindung: false,
    contract_zahlart: 0,
    createdOn: "",
    eigenvertrag: false,
    ersparnis: false,
    externalProduktId: "",
    fahrer_1_bfa: false,
    fahrer_1_familie: false,
    fahrer_1_fs_herkunft: "",
    fahrer_1_vzr: false,
    fahrer_2: false,
    fahrer_2_bfa: false,
    fahrer_2_familie: false,
    fahrer_2_fs_herkunft: "",
    fahrer_2_vzr: false,
    fahrer_3: false,
    fahrer_3_bfa: false,
    fahrer_3_familie: false,
    fahrer_3_fs_herkunft: "",
    fahrer_3_vzr: false,
    fahrer_4: false,
    fahrer_4_bfa: false,
    fahrer_4_familie: false,
    fahrer_4_fs_herkunft: "",
    fahrer_4_vzr: false,
    fahrer_5: false,
    fahrer_5_bfa: false,
    fahrer_5_familie: false,
    fahrer_5_fs_herkunft: "",
    fahrer_5_vzr: false,
    fahrer_Partner: false,
    fahrer_Partner_bfa: false,
    fahrer_Partner_fs_herkunft: "",
    fahrer_Partner_verheiratet_mit_vn: false,
    fahrer_Partner_vzr: false,
    fahrer_Sohn: false,
    fahrer_Sohn_bfa: false,
    fahrer_Sohn_fs_herkunft: "",
    fahrer_Sohn_vzr: false,
    fahrer_Tochter: false,
    fahrer_Tochter_bfa: false,
    fahrer_Tochter_fs_herkunft: "",
    fahrer_Tochter_vzr: false,
    fahrer_VN: true,
    fahrer_VN_bfa: false,
    fahrer_VN_fs_herkunft: "",
    fahrer_VN_vzr: false,
    fahrer_Weitere: false,
    fahrzeugtyp: "",
    fahrzeugtypSonstige: "",
    fremdvertrag: false,
    geschaeftsausgabe: false,
    gesellschaft: "",
    halter_ort: "",
    halter_plz: "",
    herstellerSchl: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    modellSchl: "",
    monatsBeitrag: 0,
    name: "",
    notizen: "",
    shortDescription: "",
    subtype: "",
    tarifBezeichnung: "",
    tarifMitRabattschutz: false,
    tarifTypeId: "",
    tarifgruppe: "",
    toggleSonderausstattung: false,
    toggleWohneigentum: false,
    unterlagen: false,
    versicherungsbeginn: "",
    versicherungsbeginnNeu: "",
    versicherungsende: "",
    versicherungsnehmerId: "",
    versicherungsnummer: "",
    vn_anrede: 0,
    vn_familienstand: 0,
    vn_firmenname: "",
    vn_geburtsdatum: "",
    vn_hausnummer: "",
    vn_nationalitaet: "",
    vn_ort: "",
    vn_plz: "",
    vn_strasse: "",
    vn_weitere_fahrzeuge: false,
    vorschaedenAnzahl: 0,
    zahlweise: "",
  };
  let wohnsituation = {
    analyseId: "",
    angebotsType: "",
    beitrag: 0,
    createdOn: "",
    externalProduktId: "",
    gesellschaft: "",
    id: "",
    jahresBeitrag: 0,
    lastModified: "",
    monatsBeitrag: 0,
    notizen: "",
    tarifBezeichnung: "",
    tarifTypeId: "",
    versicherungsnehmerBeide: false,
    versicherungsnehmerId: "",
    wohnflaeche: 0,
    wohngeld: 0,
    wohnung: "",
    wohnungKaltmiete: 0,
    wohnungMiete: 0,
    wohnungNebenkosten: 0,
    wohnungZurMiete: false,
  };
function emptyCardTemplate(card){
    let output = {}
    console.log("drinenenen")
    switch (card) {
        case "EINNAHMEN":
          output = sonstigeEinnahmen;
    
          break;
        case "EINKOMMEN_GEHALT":
          output = einkommenGehalt;
    
          break;
        case "EINKOMMEN_MINIJOB":
          output = einkommenGeringverdiener;
    
          break;
        case "EINKOMMEN_SELBSTAENDIGER":
          output = einkommenSelbststaendig;
    
          break;
        case "AUSGABEN":
          output = ausgaben;
    
          break;
        case "AUTOMOBILCLUB":
          output = automobilclub;
    
          break;
        case "SONSTIGE_ZAHLUNG":
          output = sonstigeZahlungsverpflichtigungen;
    
          break;
        case "KONSUMKREDIT":
          output = konsumKredit;
    
          break;
        case "BANKPRODUKTE":
          output = bankprodukte;
    
          break;
        case "VWL_BAUSPAREN":
          output = vwl;
    
          break;
        case "IMMOBILIENBESTAND":
          output = immobilienbestand;
    
          break;
        case "BETEILIGUNGEN":
          output = beteiligungenAiF;
    
          break;
        case "BU":
          output = buEuGfk;
    
          break;
        case "UNFALL":
          output = unfall;
    
          break;
        case "RISIKO":
          output = todesfall;
    
          break;
        case "DREADDISEASE":
          output = schwereKrankheiten;
    
          break;
        case "PFLEGEKOSTEN":
          output = privatePflegeversicherung;
    
          break;
        case "PFLEGERENTEN":
          output = privatePflegeversicherung;
    
          break;
        case "PFLEGETAGEGELD":
          output = privatePflegeversicherung;
    
          break;
        case "GESETZLICHE_KRANKEN":
          output = gesetzlicheKranken;
    
          break;
        case "KVV":
          output = privateKranken;
    
          break;
        case "PRIVATHAFTPFLICHT":
          output = privathaftpflicht;
    
          break;
        case "KVZ":
          output = kvZusatz;
    
          break;
        case "HUNDEHALTERHAFTPFLICHT":
          output = hundehalterhaftpflicht;
    
          break;
        case "HAUSRAT":
          output = hausrat;
    
          break;
        case "RECHTSSCHUTZ":
          output = rechtschutz;
    
          break;
        case "WOHNGEBAEUDE":
          output = wohngebaeude;
    
          break;
        case "KFZ":
          output = KFZ;
    
          break;
        case "WOHNSITUATION":
          output = wohnsituation;
    
          break;
        default:
            output ={}
          break;
      }
    return output
}

export default emptyCardTemplate